cloudhub:
  username: "ivanfons05"
  password: "Scottsdale!01"
  envid: "4ed6eae4-7006-4985-a8b9-7cb7b206c82e"
ftp:
  host: "192.168.0.15"
  port: "21"
  username: "ftpuser"
  password: "password"
  filepath: "/batchJobRecordsFile.csv"
servicenow:
  username: "admin"
  password: "@wE!kMZJmz97"
  address: "https://dev157723.service-now.com/"

objectstore:
  path: "/objectStore"

http:
  port: "8081"
encryption:
  key: "abcdef0123456789"
config:
  file: "test_email_config"


https:
  port: "8082"

kafka:
  topic: "practicetopic"
  host: "localhost:9092"

american:
  host: "training4-american-api.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "d846d01ea59640108779eaaa532d00ca"
  client_secret: "F7C5ecA48EBA449399b4B140416849B0"

delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
  
#email:
#  host: "smtp.gmail.com"
#  port: "587"
#  user: "ivanfons05@gmail.com"
#  password: "jtzhwjuswsmzngzr"

file:
  directory: "C:\\Users\\ivanf\\Documents\\MuleSoft\\input"
  fileRead: "C:\\Users\\ivanf\\Documents\\MuleSoft\\input\\records.csv"
  fileWrite: "C:\\Users\\ivanf\\Documents\\MuleSoft\\output\\recordOutput.txt"
  fileArchive: "C:\\Users\\ivanf\\Documents\\MuleSoft\\archive"
  
batch:
  fileRead: "C:\\Users\\ivanf\\Documents\\MuleSoft\\batchinput\\batchJobRecordsFile.csv"
  dir: "C:\\Users\\ivanf\\Documents\\MuleSoft\\batchinput"
  batchFileArchive: "C:\\Users\\ivanf\\Documents\\MuleSoft\\batcharchive"
  
muleRequestHttp:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  
salesforce:
  username: "ivanfons05@gmail.com"
  password: "Scottsdale!02"
  token: "lP3Wq7JTybNdKibi9AQgNPQQB"
  
  